services:

  kt:
    image: kt-dev:0.0
    volumes:
      - type: bind
        source: ../..
        target: /app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  db-data:
    external: true
    name: kt-db
