# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0056_auto_20151218_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Poll'),
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Topic'),
        ),
    ]
