# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0057_auto_20151219_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='VapitiVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vapiti_round', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('vapiti_type', models.CharField(choices=[(b'G', b'Gold'), (b'M', b'Silver Male'), (b'F', b'Silver Female')], default=b'G', max_length=1)),
                ('serial_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ktapp.Artist')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktapp.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vapitivote',
            unique_together=set([('user', 'year', 'vapiti_round', 'vapiti_type', 'serial_number')]),
        ),
    ]
