# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0058_auto_20151230_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(b'NV', b'New vote'), (b'CV', b'Change vote'), (b'DV', b'Delete vote'), (b'AW', b'Add to wishlist'), (b'RW', b'Remove from wishlist'), (b'NC', b'New comment'), (b'EC', b'Edit comment'), (b'SU', b'Signup'), (b'EP', b'Edit profile'), (b'FO', b'Follow'), (b'UF', b'Unfollow'), (b'PV', b'Poll vote'), (b'VV', b'Vapiti vote')], default=b'NV', max_length=2),
        ),
    ]
