# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0061_auto_20160120_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='number_of_actors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
