# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0063_film_genre_cache_is_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='number_of_bios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='number_of_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
