# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0065_film_genre_cache_is_docu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('where', models.CharField(max_length=32)),
                ('what', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[(b'P', b'Published'), (b'V', b'Viewed'), (b'C', b'Closed'), (b'W', b'Withdrawn')], default=b'P', max_length=1)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.PositiveSmallIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
