# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0066_banner'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX fulltext_idx_slug_cache ON ktapp_artist (slug_cache)',),
            ('DROP INDEX fulltext_idx_slug_cache ON ktapp_artist',)
        )
    ]
