# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 03:53
from __future__ import unicode_literals

from django.db import migrations
from ktapp.utils import run_sql_except_on_sqlite


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0066_banner'),
    ]

    operations = [
        run_sql_except_on_sqlite(
            sql='CREATE FULLTEXT INDEX fulltext_idx_slug_cache ON ktapp_artist (slug_cache)',
            reverse_sql='DROP INDEX fulltext_idx_slug_cache ON ktapp_artist',
        )
    ]
