# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0068_auto_20160306_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ktuser',
            name='reason_of_inactivity',
            field=models.CharField(choices=[(b'B', b'Banned'), (b'T', b'Temporarily Banned'), (b'Q', b'Quit'), (b'U', b'Unknown')], default=b'U', max_length=1),
        ),
    ]
