# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0069_auto_20160423_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='is_inner_staff',
            field=models.BooleanField(default=False),
        ),
    ]
