# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0070_ktuser_is_inner_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('url_domain', models.CharField(max_length=250)),
                ('referer', models.CharField(blank=True, max_length=250)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link_type', models.CharField(choices=[(b'LI', b'Link'), (b'IM', b'Film / IMDb'), (b'PO', b'Film / Port.hu'), (b'RT', b'Film / Rotten Tomatoes'), (b'YT', b'Film / YouTube'), (b'WE', b'Film / Wikipedia EN'), (b'WH', b'Film / Wikipedia HU'), (b'AI', b'Artist / IMDb'), (b'AE', b'Artist / Wikipedia EN'), (b'AH', b'Artist / Wikipedia HU'), (b'-', b'Other')], default=b'-', max_length=2)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ktapp.Artist')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ktapp.Film')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ktapp.Link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
