# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0071_linkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_pic', to='ktapp.Picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_profile', to='ktapp.Artist'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Film'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_type',
            field=models.CharField(choices=[(b'P', b'Poster'), (b'D', b'DVD'), (b'S', b'Screenshot'), (b'O', b'Other'), (b'A', b'Actor profile'), (b'U', b'User profile')], default=b'O', max_length=1),
        ),
    ]
