# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0072_auto_20160427_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(b'NV', b'New vote'), (b'CV', b'Change vote'), (b'DV', b'Delete vote'), (b'AW', b'Add to wishlist'), (b'RW', b'Remove from wishlist'), (b'NC', b'New comment'), (b'EC', b'Edit comment'), (b'SU', b'Signup'), (b'EP', b'Edit profile'), (b'UP', b'Upload profile pic'), (b'DP', b'Delete profile pic'), (b'FO', b'Follow'), (b'UF', b'Unfollow'), (b'PV', b'Poll vote'), (b'VV', b'Vapiti vote'), (b'NT', b'New toplist'), (b'ET', b'Edit toplist'), (b'DT', b'Delete toplist')], default=b'NV', max_length=2),
        ),
    ]
