# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0073_auto_20160428_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='iszdb_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='linkclick',
            name='link_type',
            field=models.CharField(choices=[(b'LI', b'Link'), (b'IM', b'Film / IMDb'), (b'PO', b'Film / Port.hu'), (b'RT', b'Film / Rotten Tomatoes'), (b'YT', b'Film / YouTube'), (b'WE', b'Film / Wikipedia EN'), (b'WH', b'Film / Wikipedia HU'), (b'IS', b'Film / ISZDb'), (b'AI', b'Artist / IMDb'), (b'AE', b'Artist / Wikipedia EN'), (b'AH', b'Artist / Wikipedia HU'), (b'-', b'Other')], default=b'-', max_length=2),
        ),
    ]
