# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0074_auto_20160617_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='number_of_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
