# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0076_ktuser_opinion_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='design_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
