# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0077_ktuser_design_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserCount',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('dau_count', models.PositiveIntegerField(default=0)),
                ('wau_count', models.PositiveIntegerField(default=0)),
                ('mau_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
