# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0078_activeusercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='game_mode',
            field=models.BooleanField(default=False),
        ),
    ]
