# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0080_auto_20160925_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='number_of_artists',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
