# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0081_picture_number_of_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbounce',
            name='bounced_at',
            field=models.DateField(),
        ),
    ]
