# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0084_film_main_roles_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='subscribed_to_campaigns',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='token_to_unsubscribe',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
