# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0086_emailunsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[(b'Co', b'Comment')], default=b'Co', max_length=2)),
                ('notification_subtype', models.CharField(blank=True, choices=[(b'CoRe', b'Comment reply'), (b'CoMe', b'Comment mention'), (b'CoRa', b'Comment on film you rated'), (b'CoCo', b'Comment on film you commented'), (b'CoWi', b'Comment on film you wished')], max_length=4)),
                ('is_read', models.BooleanField(default=False)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Film')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noti_source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='notification',
            index_together=set([('target_user', 'created_at')]),
        ),
    ]
