# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0087_auto_20161206_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='unread_notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
