# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0089_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Poll'),
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktapp.Topic'),
        ),
    ]
