# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0093_auto_20180607_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='validated_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
