# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0095_auto_20181111_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='future_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
