# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-31 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0098_auto_20190802_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='vapiti_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
