# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0101_auto_20240207_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='given_at',
            field=models.DateField(),
        ),
    ]
