# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0102_auto_20240207_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateField(),
        ),
    ]
