# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0103_auto_20240207_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='is_ex_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='is_ex_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ktuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
