# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-19 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0105_remove_ktuser_is_inner_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='OldMessage',
        ),
    ]
