# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-11-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0108_appconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='birthday_party_announced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='birthday_party_announcement_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='birthday_party_announcement_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
